name: Prebuilt repo + Snyk Security Scanning (OS, Code, Docker, IaC)

# Runs 4 Snyk Producfts (Code, Open Sourgce, Container, IaC)
# Snyk installation via npm
# Node.js version: 18.4
# Outputs the results to the pipeline and in SARIF-format to the security tab

# Prerequisites:
# - Set a SNYK_TOKEN and a SNYK_ORG in the pipelines secrets

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js for installing Snyk 
      uses: actions/setup-node@v2
      with:
        node-version: 18.4

    # Install & prepare Snyk
    - run: npm install --location=global snyk
    
    #  This OPTIONAL step will configure the Snyk CLI to connect to the EU instance of Snyk
    #- run: snyk config set use-base64-encoding=true
    #- run: snyk config set endpoint='https://app.eu.snyk.ito/api'
      
    - run: snyk auth ${{ secrets.SNYK_TOKEN }}
    - name: install snyk-to-html
      run: | 
               npm install snyk-to-html -g 
   # - name: Snyk Open Source Scanning
     ## continue-on-error: true
    - name: Install SNyk Filter
      run: npm i -g snyk-filter

    - name: Snyk filter test
      run: snyk test --json | snyk-filter --json | snyk-to-html -o snykfilter.html 
      continue-on-error: true
      
    - name: SNyk SCA Test
      run: 
          snyk test --json | snyk-to-html -o SnykOSS.html
 
    
          
    - name: Snyk Code Scanning
      run: snyk code test --json | snyk-to-html -o snykcode.html 
      continue-on-error: true
    

    - name: Build the Docker Image
      run: docker build . --file Dockerfile --tag sladey01/ghpipeline:latest

    - name: Snyk Container Scanning
      run: snyk container test docker.io/sladey01/ghpipeline:latest -json | snyk-to-html -o snykcont.html      
      continue-on-error: true
    

    - name: Snyk Infrastructure-as-Code Scanning
      run: snyk iac test --json | snyk-to-html -o snykiac.html
      continue-on-error: true

    

    - name: Use the Upload Artifact GitHub Action
      uses: actions/upload-artifact@v4
      with:
          name: results
          path: ./*.html   
